repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        args: # arguments to configure black
          - --line-length=120
          - --include='\.pyi?$'
        # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.800
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
-   repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args:
          - --filter-files
          - --profile=black
        exclude: ^(.idea/)
-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language: system
        types: [python]
        args: # arguments to configure flake8
          # making isort line length compatible with black
          - "--max-line-length=120"

          # Code complexity
          - "--max-complexity=18"

          # Ecluded files
          - "--exclude=tests/conftest.py"

          # these are errors that will be ignored by flake8
          # check out their meaning here
          # https://flake8.pycqa.org/en/latest/user/error-codes.html
          - "--ignore=W503"
